code --install-extension DavidAnson.vscode-markdownlint
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-material-theme
code --install-extension josin.kusto-syntax-highlighting
code --install-extension leizongmin.node-module-intellisense
code --install-extension maty.vscode-mocha-sidebar
code --install-extension mikestead.dotenv
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azurecli
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsts.team
code --install-extension msazurermtools.azurerm-vscode-tools
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PeterJausovec.vscode-docker
code --install-extension redhat.vscode-yaml
code --install-extension spoonscen.es6-mocha-snippets
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zhuangtongfa.Material-theme
